version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
        POSTGRES_DB: "Travel"
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - sdt-part2-practice

  rails:
    container_name: rails
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - rails-data:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  pg-data:
  rails-data:

networks:
  sdt-part2-practice:
